### ISSUE TITLE
basket holder is bad

### ISSUE THREAD

**Issue by greyltc** [AFMD/smallProjects#5]
@giulio-mazzotta you did bad with the basket in this commit: f64ed29a7d8e9fc7b34925da3f64592418fa8339
please fix asap

__IT WONT FIT IN MY BIKE BASKET__

**Comment by giulio-mazzotta** [comment]
Thanks Grey, your comment is really useful.

I'll update the readme.md to specify this is not for bikes.

Giulio

**Comment by giulio-mazzotta** [comment]
@greyltc this has now been fixed with commit: a8acee2
